language: node_js
node_js:
  - "0.12"
before_install:
  - npm install travis-ci
after_success:
  - if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then node trigger-build.js; fi
